#                   _
#    __ _____ ____ (_)
#   / // / _ `/_ // /
#   \_, /\_,_//__/_/
#  /___/
# yazi keymap overrides

[manager]
prepend_keymap = [
	# Misc Integration
	{ on = ["<A-a>"],      run = "shell --block dragon-drop --all $@" },
]

