#                   _
#    __ _____ ____ (_)
#   / // / _ `/_ // /
#   \_, /\_,_//__/_/
#  /___/
# yazi runtime config

[manager]
sort_dir_first = true
linemode = "size"
show_symlink = true

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true },
]
open = [
	{ run = 'xdg-open "$@"' },
]

