#!/bin/sh

# utility replacement
alias l="exa -lah --color=auto --group-directories-first" \
	ls="exa -h --color=auto --group-directories-first" \
	grep="rg";

# basic
alias c="clear" \
	f="\$FILE" \
	e="\$EDITOR" \
	v="\$EDITOR" \
	i="htop -t" \
	lg="l | grep" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	hg="history | grep" \
	mkd="mkdir -pv" \
	manp="man 1p" \
	duse="du -chH | sort -h" \
	rduse="du -chH | sort -rh" \
	lb="lsblk -o MODE,TYPE,HOTPLUG,FSTYPE,FSVER,NAME,MOUNTPOINT,LABEL,STATE,FSUSE%,FSUSED,FSSIZE,SIZE,MODEL,PARTUUID" \
	sdn="sudo shutdown -h now" \
	lap="ps -u" \
	kap="killall" \
	mimetype="file --mime-type" \
	xdgtype="xdg-mime query filetype" \
	xdgdefault="xdg-mime query default" \
	lamp="ps -u \$(whoami)" \
	kamp="killall -u \$(whoami)";

# networking
alias lptl="sudo lsof -i -P -n | grep LISTEN";

# git
alias g="git" \
	gd="git diff" \
	gds="git diff --staged" \
	gdh="git diff HEAD" \
	gsb="git status -sb" \
	gss="git status -s" \
	gst="git status" \
	gl="git pull" \
	gulp="git submodule foreach git pull origin master" \
	ga="git add" \
	grm="git rm" \
	gcmsg="git commit -m" \
	gcsmg="git commit -m" \
	gua="git remote | xargs -L1 git push --all" \
	gpp="git pull && git push origin master";

# yay / pacman / misc. arch
alias yg="yay -Qs | grep" \
	yq="yay -Qi" \
	yps="yay -Ps" \
	yys="yay -Syu" \
	yysp="yay -Syu && poweroff" \
	yysr="yay -Syu && reboot" \
	yyf="yay -Syyu" \
	yls="yay -Ql" \
	ycl="yay -Yc && paccache -r" \
	lsp="pacman -Qett --color=always | less" \
	pacwhen="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort" \
	ifck="informant check" \
	ifls="informant list" \
	ifrd="informant read" \
	lsff="fc-list : family";

# other package managers
alias cg="conda list | grep" \
	car="conda activate" \
	cdr="conda deactivate" \
	cup="conda update conda pip" \
	cua="conda update --all" \
	ccl="conda clean --yes --all";

# trash-cli
alias tdd="trash-put" \
	tls="trash-list | $PAGER" \
	tre="trash-restore" \
	tem="trash-empty";

# program aliases
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc\$(date +%s)" \
	x="sxiv -ft *" \
	s="\$HOME/.local/bin/uitools/lspaths | fzf --reverse --info=inline --preview='pistol {}'" \
	ytd="youtube-dl --add-metadata -i -o '\$HOME/Downloads/%(upload_date)s-%(title)s.%(ext)s'" \
	ytda="youtube-dl --add-metadata -i -x -f 'bestaudio/best' -o '\$HOME/Music/%(upload_date)s-%(title)s.%(ext)s'" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	ffmpeg="ffmpeg -hide_banner" \
	dt="dust" \
	dt="dust -d 3" \
	grex="grex -r" \
	appsync="rsync -avxP" \
	mirsync="rsync -avxP --delete" \
	shck="shellcheck" \
	vd="vidir" \
	pwi="sudo powertop" \
	nv="nvidia-smi" \
	nvw="watch -n 2 nvidia-smi" \
	nvi="nvtop" \
	jup="jupyter notebook --ip=127.0.0.1 --port=8888";

# combo aliases
alias cl="ycl && ccl"; # Clear all caches


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Alias neovim as vim if present.
sd() {
	RES="$(s --header='Search Directory')";
	FILEPATH=$([ -d "$RES" ] && echo "$RES" || dirname "$RES");
	cd "$FILEPATH" || return;
}
so() {
	s --header='Open File' | xargs -r "$OPENER"; # TODO - get this to open files with vim in the same terminal window
}
sg() {
	RES="$(s --header='Grep File')";
	grep "$1" "$RES";
}
se() {
	s --header='Edit File' | xargs -r "$EDITOR";
}
trm() {
	TO_REMOVE=$(trash-list | fzf --reverse --info=inline --header='Delete File' | awk '{print $NF}');
	trash-rm "$TO_REMOVE";
}
#vf() {
#	fzf | xargs -r -I % $EDITOR % ;
#}
ifi() {
	CHOSEN=$(ifls | fzf | sed 's/:.*//');
	ifrd "$CHOSEN";
}
#shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
#sv() { vcopy "$(du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf)" ;}
