#!/bin/sh

# basic
alias c="clear" \
	f="\$FILE" \
	e="\$EDITOR" \
	v="\$EDITOR" \
	l="ls -lahN --color=auto --group-directories-first" \
	lg="ls -lahN --color=auto --group-directories-first | grep" \
	ls="ls -hN --color=auto --group-directories-first" \
	i="htop -t" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	hg="history | grep" \
	mkd="mkdir -pv" \
	manp="man 1p" \
	duse="du -chH | sort -h" \
	rduse="du -chH | sort -rh" \
	lb="lsblk -o MODE,TYPE,HOTPLUG,FSTYPE,FSVER,NAME,LABEL,STATE,FSUSE%,FSUSED,FSSIZE,SIZE,MODEL,PARTUUID" \
	appsync="rsync -avxP" \
	mirsync="rsync -avxP --delete" \
	vd="vidir" \
	sdn="sudo shutdown -h now" \
	lap="ps -u" \
	kap="killall" \
	mimetype="file --mime-type" \
	xdgtype="xdg-mime query filetype" \
	xdgdefault="xdg-mime query default" \
	lamp="ps -u \$(whoami)" \
	kamp="killall -u \$(whoami)";

# networking
alias lptl="sudo lsof -i -P -n | grep LISTEN";

# git
alias g="git" \
	gsb="git status -sb" \
	gss="git status -s" \
	gst="git status" \
	gl="git pull" \
	gulp="git submodule foreach git pull origin master" \
	ga="git add" \
	grm="git rm" \
	gcmsg="git commit -m" \
	gcsmg="git commit -m" \
	gua="git remote | xargs -L1 git push --all" \
	gpp="git pull && git push origin master";

# yay / pacman / misc. arch
alias yg="yay -Qs | grep" \
	yq="yay -Qi" \
	yps="yay -Ps" \
	yys="yay -Syu" \
	yyf="yay -Syyu" \
	yls="yay -Ql" \
	ycl="yay -Yc && paccache -r" \
	lsp="pacman -Qett --color=always | less" \
	pacwhen="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort" \
	ifck="informant check" \
	ifls="informant list" \
	ifrd="informant read" \
	lsff="fc-list : family";

# other package managers
alias cg="conda list | grep" \
	car="conda activate" \
	cdr="conda deactivate" \
	cup="conda update conda pip" \
	cua="conda update --all" \
	ccl="conda clean --yes --all";

# other
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc\$(date +%s)" \
	x="sxiv -ft *" \
	lspaths="$HOME/.local/bin/uitools/listpaths" \
	ytd="youtube-dl --add-metadata -i -o '$HOME/Downloads/%(upload_date)s-%(title)s.%(ext)s'" \
	ytda="youtube-dl --add-metadata -i -x -f 'bestaudio/best' -o '$HOME/Music/%(upload_date)s-%(title)s.%(ext)s'" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	ffmpeg="ffmpeg -hide_banner" \
	grex="grex -r" \
	nv="nvidia-smi" \
	nvw="watch -n 2 nvidia-smi" \
	jup="jupyter notebook --ip=127.0.0.1 --port=8888";

# combo aliases
alias cl="ycl && ccl"; # Clear all caches


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Alias neovim as vim if present.
s() {
	#RES="$(~/.local/bin/uitools/listpaths | fzf --reverse --header='Jump to location')";
	#[ -d "$RES" ] && cd $RES || setsid $OPENER $RES;
	#setsid $OPENER $RES;
	lspaths | fzf --reverse --header='Open File' | xargs -r setsid "$OPENER"; # TODO - get this to open files with vim in the same terminal window
}
se() {
	lspaths | fzf --reverse --header='Edit File' | xargs -r "$EDITOR";
}
#vf() {
#	fzf | xargs -r -I % $EDITOR % ;
#}
ifi() {
	CHOSEN=$(ifls | fzf | sed 's/:.*//');
	ifrd "$CHOSEN";
}
#shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
#sv() { vcopy "$(du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf)" ;}
