#!/bin/sh

# replace utils with rust alternatives
alias l="exa -lah --color=auto --group-directories-first" \
	ls="exa -h --color=auto --group-directories-first" \
	grep="rg" \
	cat="bat --theme=zenburn" \
	find="fd -HI --ignore-file \"\$HOME\"/.config/fd/ignore_file";

# basic
alias f="\$FILE" \
	e="\$EDITOR" \
	v="\$EDITOR" \
	c="clear" \
	i="htop -t" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	lg="l | grep" \
	mkd="mkdir -pv" \
	manp="man 1p" \
	duse="du -chH | sort -h" \
	lb="lsblk -o MODE,TYPE,HOTPLUG,FSTYPE,FSVER,NAME,MOUNTPOINT,LABEL,STATE,FSUSE%,FSUSED,FSSIZE,SIZE,MODEL,PARTUUID" \
	kafter="timeout -sTERM" \
	sdn="sudo shutdown -h now" \
	lap="ps -u" \
	kap="killall" \
	mimetype="file --mime-type" \
	xdgtype="xdg-mime query filetype" \
	xdgdefault="xdg-mime query default" \
	xorgfocusinfo="xprop -id \`xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print \$NF}'\`" \
	today="date '+%Y-%m-%d'" \
	myip="curl -q ifconfig.co" \
	watch2="watch -n 2 " \
	lamp="ps -u \`whoami\`" \
	kamp="kap -u \`whoami\`";

# systemd
alias sstart="sudo systemctl start" \
	senable="sudo systemctl enable" \
	sstop="sudo systemctl stop" \
	sstatus="systemctl status";

# networking
alias lptl="sudo lsof -i -P -n | grep LISTEN";

# git
alias g="git" \
	gd="g diff" \
	gc="g clone" \
	gds="gd --staged" \
	gdh="gd HEAD" \
	gdl="g clone" \
	gls="g log" \
	gst="g status" \
	gss="gst -sb" \
	gl="g pull" \
	gp="g push" \
	gulp="g submodule foreach git pull origin master" \
	ga="g add" \
	gr="g remote" \
	grm="g rm" \
	gcmsg="g commit -m" \
	gua="gr | xargs -L1 git push --all" \
	glp="gl && gp";

# yay / pacman / misc. arch
alias y="yay" \
	yg="y -Qs | grep" \
	yq="y -Qi" \
	yps="y -Ps" \
	yys="y -Syu" \
	yysp="y -Syu && poweroff" \
	yysr="y -Syu && reboot" \
	yyf="y -Syyu" \
	yrm="y -Rsn" \
	yls="y -Ql" \
	ycl="y -Yc && paccache -r" \
	pacls="pacman -Qett --color=always" \
	pacwhen="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort" \
	pacmirrup="sudo reflector --country 'United States' --latest 200 --age 24 --sort rate --save /etc/pacman.d/mirrorlist && rm -f /etc/pacman.d/mirrorlist.pacnew" \
	ifck="informant check" \
	ifls="informant list" \
	ifrd="informant read" \
	ifi="ifrd \"\$(ifls | fzf | sed 's/:.*//')\"" \
	lsfont="fc-list" \
	lsfontfam="lsfont : family";

# conda
alias cg="conda list | grep" \
	cq="conda info" \
	cls="conda list" \
	car="conda activate" \
	cdr="conda deactivate" \
	cup="conda update conda pip" \
	cua="conda update --all" \
	crm="conda remove" \
	ccl="conda clean --yes --all";

# trash-cli
alias tdd="trash-put" \
	tls="trash-list | \$PAGER" \
	tre="trash-restore" \
	trm="trash-rm \"\$(trash-list | fzf --reverse --info=inline --header='Delete File' | awk '{print \$NF}')\"" \
	tem="trash-empty";

# search aliases
alias lspaths="fd -HI --ignore-file \"\$HOME\"/.config/fd/ignore_file" \
	s="lspaths | fzf --reverse --info=inline --preview='pistol {}'" \
	se="\$EDITOR \"\$(s --header='Edit File')\"" \
	sd="moveto \"\$(s --header='Search Directory')\"" \
	so="\$OPENER \"\$(s --header='Open File')\"" \
	sr="\$READER \"\$(fd -I -t 'f' '.' \"\$READING\" | sed \"s|\$READING\/||\" | fzf --reverse --info=inline --preview=\"pistol \$READING/{}\" --header='Select Reading' | sed \"s|^|\$READING\/|\")\"";

# history aliases
alias h="history" \
	hg="h | grep" \
	hs="h | fzf --tac --info=inline --header='Search Command' | sed 's/^[0-9]*\s*//g'" \
	hi="xdotool type --delay 0 \"\$(hs)\" && clear";

# program aliases
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc\$(date +%s)" \
	x="sxiv -ft *" \
	ytd="youtube-dl --add-metadata -i -o '\$HOME/Downloads/%(upload_date)s-%(title)s.%(ext)s'" \
	ytda="youtube-dl --add-metadata -i -x -f 'bestaudio/best' -o '\$HOME/Music/%(upload_date)s-%(title)s.%(ext)s'" \
	ffmpeg="ffmpeg -hide_banner" \
	dt="dust" \
	dt3="dt -d 3" \
	grex="grex -r" \
	appsync="rsync -avxP" \
	mirsync="rsync -avxP --delete" \
	shck="shellcheck" \
	viewdoc="fzf | pandoc -f docx -t pdf | zathura -" \
	vd="vidir" \
	pwi="sudo powertop" \
	nv="nvidia-smi" \
	nvw="watch2 nv" \
	nvi="nvtop" \
	jup="jupyter notebook --ip=127.0.0.1 --port=8888";

# combo aliases
alias cl="ycl && ccl"; # Clear all caches


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Alias neovim as vim if present.
moveto() {
	FILEPATH=$([ -d "$1" ] && echo "$1" || dirname "$1");
	cd "$FILEPATH" || return;
}
sg() {
	RES="$(s --header='Grep File')";
	grep "$1" "$RES";
}
tunder() {
	for i in *' '*; do   mv "$i" `echo $i | sed -e 's/ /_/g'`; done
}

#vf() {
#	fzf | xargs -r -I % $EDITOR % ;
#}
#shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
#sv() { vcopy "$(du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf)" ;}
