#!/bin/sh
#      __
#     / /_  _________ _      ______ ___
#    / __ \/ ___/ __ \ | /| / / __ `__ \
#   / /_/ (__  ) /_/ / |/ |/ / / / / / /
#  /_.___/____/ .___/|__/|__/_/ /_/ /_/
#            /_/
# binary space partitioning window manager runtime config.

# Set monitor workspaces (called desktops in bspwm)
# TODO - check the monitors that are connected and enabled,
# disperse desktops accordingly what I have here now won't work
# as originally intended.
# bspc monitor DP-0    -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor HDMI-0  -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 0

HDMI_ACTIVE=$(xrandr | grep ' connected' | grep 'HDMI-0' | awk '{print $1}' | xargs);
DP_ACTIVE=$(xrandr | grep ' connected' | grep 'DP-0' | awk '{print $1}' | xargs);
GPU_MODE=$(optimus-manager --print-mode | awk '{print $NF}' | xargs);

if [ "$GPU_MODE" = 'nvidia' ] ; then
	if [ -n "$DP_ACTIVE" ] ; then
		bspc monitor DP-0    -d 1 2 3 4 5 6 7 8 9 0;
	elif [ -n "$HDMI_ACTIVE" ] ; then
		bspc monitor HDMI-0  -d 1 2 3 4 5 6 7 8 9 0;
	else
		bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0;
	fi;
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0;
fi;


# Global Settings
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
#bspc config pointer_modifier shift
bspc focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged monitors true
bspc config merge_overlapping_monitors false
#bspc config normal_frame_opacity 1.0
#bspc config focused_frame_opacity 0.05
#bspc config focused_private_border_color "#35BF5C"
bspc config focused_border_color "#99CC99"
bspc config normal_border_color "#000000"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"


# Desktop Settings
bspc config top_padding 32
bspc config bottom_padding 32
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 8


# Rules
bspc rule -r  "*"	# Clear all rules
bspc rule -a Next state=tiled
bspc rule -a Nyxt state=tiled
bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
