[default_view]
keymap = [
	# Cursor Movement
	{ keys = ["arrow_up"],        command = "cursor_move_up" },
	{ keys = ["arrow_down"],      command = "cursor_move_down" },
	{ keys = ["arrow_left"],      command = "cd .." },
	{ keys = ["arrow_right"],     command = "open" },
	{ keys = ["k"],               command = "cursor_move_up" },
	{ keys = ["j"],               command = "cursor_move_down" },
	{ keys = ["h"],               command = "cd .." },
	{ keys = ["l"],               command = "open" },
	{ keys = ["\n"],              command = "open" },
	{ keys = ["page_up"],         command = "cursor_move_page_up" },
	{ keys = ["page_down"],       command = "cursor_move_page_down" },
	{ keys = ["ctrl+u"],          command = "cursor_move_page_up 0.5" },
	{ keys = ["ctrl+d"],          command = "cursor_move_page_down 0.5" },
	{ keys = ["H"],               command = "cursor_move_page_home" },
	{ keys = ["L"],               command = "cursor_move_page_middle" },
	{ keys = ["M"],               command = "cursor_move_page_end" },

	# Cursor Movement (Parent)
	{ keys = ["["],               command = "parent_cursor_move_up" },
	{ keys = ["]"],               command = "parent_cursor_move_down" },

	# Go (g*)
	{ keys = ["g","g"],           command = "cursor_move_home" },
	{ keys = ["g","e"],           command = "cursor_move_end" },
	{ keys = ["g","r"],           command = "cd /" },
	{ keys = ["g","f"],           command = "cd ~/Downloads" },
	{ keys = ["g","d"],           command = "cd ~/Documents" },
	{ keys = ["g","p"],           command = "cd ~/Projects" },
	{ keys = ["g","h"],           command = "cd ~/" },
	{ keys = ["home"],            command = "cd ~/" },
	{ keys = ["end"],             command = "cd /" },

	# Tabs
	{ keys = ["ctrl+t"],          command = "new_tab" },
	{ keys = ["alt+t"],           command = "new_tab --cursor" },
	{ keys = ["T"],               command = "new_tab --current" },
	{ keys = ["W"],               command = "close_tab" },
	{ keys = ["ctrl+w"],          command = "close_tab" },
	{ keys = ["q"],               command = "close_tab" },
	{ keys = ["\t"],              command = "tab_switch 1" },
	{ keys = ["backtab"],         command = "tab_switch -1" },

	# File Sorting (s*)
	{ keys = ["s","r"],           command = "sort reverse" },
	{ keys = ["s","l"],           command = "sort lexical" },
	{ keys = ["s","m"],           command = "sort mtime" },
	{ keys = ["s","n"],           command = "sort natural" },
	{ keys = ["s","s"],           command = "sort size" },
	{ keys = ["s","e"],           command = "sort ext" },

	# Searching
	{ keys = ["/"],               command = ":search " },
	{ keys = ["|"],               command = ":search_inc " },
	{ keys = ["\\"],              command = ":search_glob " },
	{ keys = ["S"],               command = "search_fzf" },
	{ keys = ["C"],               command = "subdir_fzf" },
	{ keys = ["n"],               command = "search_next" },
	{ keys = ["N"],               command = "search_prev" },

	# Selection
	{ keys = [" "],               command = "select --toggle=true" },
	{ keys = ["a"],               command = "select --all=true --toggle=true" },
	{ keys = ["%"],               command = "select --all=true --toggle=true" },

	# Yank (Copy) / Paste
	{ keys = ["y"],               command = "copy_files" },
	{ keys = ["p"],               command = "paste_files --overwrite=false" },
	# { keys = ["y","n"],           command = "copy_filename" },
	# { keys = ["y","."],           command = "copy_filename_without_extension" },
	# { keys = ["y","p"],           command = "copy_filepath" },
	# { keys = ["y","d"],           command = "copy_dirpath" },
	# { keys = ["d","d"],           command = "cut_files" },
	# { keys = ["o"],               command = "paste_files --overwrite=true" },

	# Trashy Integration
	{ keys = ["delete"],          command = "shell trash put %s" },
	{ keys = ["t","d","d"],       command = "shell trash put %s" },
	{ keys = ["t","l","s"],       command = "shell trash list" },
	{ keys = ["t","e","m"],       command = "shell empty --all" },

	# Misc Integration
	{ keys = [":"],               command = ":" },
	{ keys = [";"],               command = ":" },
	{ keys = ["'"],               command = ":shell " },
	{ keys = ["e"],               command = "shell helix %s" },
	{ keys = ["r"],               command = "shell vidir %s" },
	{ keys = ["c","d"],           command = ":cd " },
	{ keys = ["m","k"],           command = ":mkdir " },

	# Hidden and Help
	{ keys = ["R"],               command = "reload_dirlist" },
	{ keys = ["z","h"],           command = "toggle_hidden" },
	{ keys = ["ctrl+h"],          command = "toggle_hidden" },
	{ keys = ["?"],               command = "help" },
	{ keys = ["i"],               command = "show_tasks --exit-key=i" },
	{ keys = ["="],               command = "set_mode" },

	# Quitting
	{ keys = ["ctrl+c"],          command = "quit" },
	{ keys = ["Q"],               command = "quit --output-current-directory" },
]

[task_view]
keymap = [
	{ keys = ["arrow_up"],        command = "cursor_move_up" },
	{ keys = ["arrow_down"],      command = "cursor_move_down" },
	{ keys = ["k"],               command = "cursor_move_up" },
	{ keys = ["j"],               command = "cursor_move_down" },
	{ keys = ["g","g"],           command = "cursor_move_home" },
	{ keys = ["g","e"],           command = "cursor_move_end" },
	{ keys = ["i"],               command = "show_tasks" },
	{ keys = ["escape"],          command = "show_tasks" },
]

[help_view]
keymap = [
	{ keys = ["arrow_up"],        command = "cursor_move_up" },
	{ keys = ["arrow_down"],      command = "cursor_move_down" },
	{ keys = ["k"],               command = "cursor_move_up" },
	{ keys = ["j"],               command = "cursor_move_down" },
	{ keys = ["g","g"],           command = "cursor_move_home" },
	{ keys = ["g","e"],           command = "cursor_move_end" },
	{ keys = ["i"],               command = "show_tasks" },
	{ keys = ["escape"],          command = "show_tasks" },
]