[tabs.styles.active]
bg = "black"
fg = "yellow"
bold = true

[regular]
fg = "white"

[directory]
fg = "light_yellow"
bold = false

[link]
fg = "cyan"
bold = false

[socket]
fg = "light_magenta"
bold = false

[executable]
fg = "green"
bold = false

[link_invalid]
fg = "red"
bold = false

[selection]
fg = "white"
bg = "black"
bold = true

[ext]
pdf.fg = "blue"
md.fg = "white"

bmp.fg = "blue"
gif.fg = "blue"
heic.fg = "blue"
jpg.fg = "blue"
jpeg.fg = "blue"
pgm.fg = "blue"
png.fg = "blue"
ppm.fg = "blue"
svg.fg = "blue"

wav.fg = "blue"
flac.fg = "blue"
mp3.fg = "blue"
amr.fg = "blue"
avi.fg = "blue"
flv.fg = "blue"
m3u.fg = "blue"
m4a.fg = "blue"
m4v.fg = "blue"

mkv.fg = "blue"
mov.fg = "blue"
mp4.fg = "blue"
mpg.fg = "blue"
rmvb.fg = "blue"
webm.fg = "blue"
wmv.fg = "blue"

c.fg = "light_green"
cpp.fg = "light_green"
sh.fg = "light_green"
java.fg = "light_green"
py.fg = "light_green"
jl.fg = "light_green"
latex.fg = "light_green"

log.fg = "gray"

# 7z.fg = "red"
# bz2.fg = "red"
# gz.fg = "red"
# rar.fg = "red"
# tar.fg = "red"
# tgz.fg = "red"
# xz.fg = "red"
# zip.fg = "red"
