#     __       ___
#    / /  ___ / (_)_ __
#   / _ \/ -_) / /\ \ /
#  /_//_/\__/_/_//_\_\
# Helix text editor runtime config.

theme = "noctis_bordo" # gruvbox, gruvbox_dark_hard, pop-dark, everforest_dark, onedark, autumn, bogster, noctis_bordo, rasmus, tokyonight_storm

#[keys.normal]
#"#" = "toggle-comments" # TODO figure out how to map pound sign

[editor]
line-number = "relative"
true-color = true
color-modes = true

[editor.statusline]
left = ["spacer", "mode", "selections", "position"]
center = ["spinner", "diagnostics"]
right = ["position-percentage", "file-name", "file-encoding", "file-type", "spacer"]

#[editor.indent-guides]
#render = true
#character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = ">"
tabpad = "-"
newline = "¬"